#!/bin/bash

read -p "enter email: " EMAIL
read -p "enter nama : " FILE

mkdir $FILE
openssl req -new -newkey rsa:2048 -subj "/emailAddress=$EMAIL" -out $FILE/$FILE.csr -keyout $FILE/$FILE.key

openssl ca -config personal-ca.conf -in ./$FILE/$FILE.csr -out ./$FILE/$FILE.crt -extensions client_reqext -days 365

cat $FILE/$FILE.crt certs/intermediate-ca.crt certs/root-ca.crt > $FILE/$FILE-chain.crt
openssl pkcs12 -export -out $FILE/$FILE.p12 -in $FILE/$FILE-chain.crt -inkey $FILE/$FILE.key

